name: Amiberry
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform to build Amiberry for'
        required: true
      distro:
        description: 'Debian version index to build Amiberry for'
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.platform }}-${{ github.event.inputs.distro }}
  cancel-in-progress: true
jobs:
  rpi1_buster:
    if: ( github.event.inputs.platform == 'rpi1' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 5 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi1 -d 5
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi1.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/buster/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/buster/testing/","https://dietpi.com/downloads/binaries/buster/testing/amiberry_rpi1.deb"]}'
  rpi1_bullseye:
    if: ( github.event.inputs.platform == 'rpi1' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 6 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi1 -d 6
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi1.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bullseye/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bullseye/testing/","https://dietpi.com/downloads/binaries/bullseye/testing/amiberry_rpi1.deb"]}'
  rpi1_bookworm:
    if: ( github.event.inputs.platform == 'rpi1' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 7 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi1 -d 7
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi1.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bookworm/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bookworm/testing/","https://dietpi.com/downloads/binaries/bookworm/testing/amiberry_rpi1.deb"]}'
  rpi2_buster:
    if: ( github.event.inputs.platform == 'rpi2' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 5 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi2 -d 5
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi2.deb --key ~.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/buster/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/buster/testing/","https://dietpi.com/downloads/binaries/buster/testing/amiberry_rpi2.deb"]}'
  rpi2_bullseye:
    if: ( github.event.inputs.platform == 'rpi2' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 6 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi2 -d 6
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi2.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bullseye/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bullseye/testing/","https://dietpi.com/downloads/binaries/bullseye/testing/amiberry_rpi2.deb"]}'
  rpi2_bookworm:
    if: ( github.event.inputs.platform == 'rpi2' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 7 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi2 -d 7
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi2.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bookworm/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bookworm/testing/","https://dietpi.com/downloads/binaries/bookworm/testing/amiberry_rpi2.deb"]}'
  rpi3_buster:
    if: ( github.event.inputs.platform == 'rpi3' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 5 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi3 -d 5
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi3.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/buster/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/buster/testing/","https://dietpi.com/downloads/binaries/buster/testing/amiberry_rpi3.deb"]}'
  rpi3_bullseye:
    if: ( github.event.inputs.platform == 'rpi3' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 6 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi3 -d 6
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi3.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bullseye/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bullseye/testing/","https://dietpi.com/downloads/binaries/bullseye/testing/amiberry_rpi3.deb"]}'
  rpi3_bookworm:
    if: ( github.event.inputs.platform == 'rpi3' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 7 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi3 -d 7
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi3.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bookworm/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bookworm/testing/","https://dietpi.com/downloads/binaries/bookworm/testing/amiberry_rpi3.deb"]}'
  rpi4_buster:
    if: ( github.event.inputs.platform == 'rpi4' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 5 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi4 -d 5
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi4.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/buster/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/buster/testing/","https://dietpi.com/downloads/binaries/buster/testing/amiberry_rpi4.deb"]}'
  rpi4_bullseye:
    if: ( github.event.inputs.platform == 'rpi4' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 6 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi4 -d 6
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi4.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bullseye/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bullseye/testing/","https://dietpi.com/downloads/binaries/bullseye/testing/amiberry_rpi4.deb"]}'
  rpi4_bookworm:
    if: ( github.event.inputs.platform == 'rpi4' || github.event.inputs.platform == 'all' ) && ( github.event.inputs.distro == 7 || github.event.inputs.distro == 'all' )
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Start build container
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/Amiberry/container_build.bash")" 'DietPi-Build_Amiberry' -p rpi4 -d 7
    - name: Upload package
      run: |
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519'
        curl -T rootfs/amiberry_rpi4.deb --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com/bookworm/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/bookworm/testing/","https://dietpi.com/downloads/binaries/bookworm/testing/amiberry_rpi4.deb"]}'
