name: gogs
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions: {}
jobs:
  build:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: sh
        working-directory: /dev/shm
    steps:
    - name: Build
      run: sudo bash -c "G_GITOWNER=$GITHUB_REPOSITORY_OWNER G_GITBRANCH=${GITHUB_REF#refs/heads/}; $(curl -sSf "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/software/gogs/container_build.bash")" 'DietPi-Build_Gogs' -a 1 -d 7
    - name: Upload
      run: |
        mkdir ~/.ssh
        umask 377
        echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts
        echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_ed25519
        curl -T rootfs/gogs_armv6.zip --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com:29248/all/'
        curl -T rootfs/gogs_armv6l.7z --key ~/.ssh/id_ed25519 'sftp://github@ssh.dietpi.com:29248/all/'
        curl 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache' -H 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' -H 'Content-Type: application/json' \
        --data '{"files":["https://dietpi.com/downloads/binaries/all/","https://dietpi.com/downloads/binaries/all/gogs_armv6.zip","https://dietpi.com/downloads/binaries/all/gogs_armv6l.7z"]}'
